sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib numpy scipy pytest pytest-cov
  - pip install coveralls

script:
  - py.test test_energy_markets.py test_model_equilibrium.py
